[tool.poetry]
name = "status-pod"
version = "0.1.0"
description = ""
authors = ["i.mikhailov"]

[tool.poetry.dependencies]
python = "^3.9"
selenium = "^3.141.0"
python-dotenv = "^0.18.0"
python-telegram-bot = "^13.7"
youtube_dl = "^2021.6.6"
fastapi = "^0.66.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
